name: "BioJulia"
description: "The Bioinformatics and Computational Biology infrastructure for the Julia programming language."

pkgname: Bio.jl
avname: bio-jl

paginate: 10

url: "https://biojulia.github.io/Bio.jl"
