# WARNING: This file was generated from gff3.rl using ragel. Do not edit!
#
# Generic Feature Format Version 3 (GFF3)
# =======================================
#
# http://www.sequenceontology.org/gff3.shtml

immutable GFF3 <: FileFormat end

	type GFF3Metadata
	source::StringField
	# use "kind" instead of "type" since "type" is a keyword of Julia
	kind::StringField
	score::Nullable{	Float64}
phase::Nullable{Int}
attributes::StringField
end

	function 	GFF3Metadata()
	return GFF3Metadata("", "", NaN, 0, "")
end

function Base.copy(metadata::GFF3Metadata)
	return GFF3Metadata(
	copy(metadata.source),
	copy(metadata.kind),
	metadata.score,
	metadata.phase,
	copy(metadata.attributes)
	)
end

"An `Interval` with associated metadata from a GFF3 file"
typealias GFF3Interval Interval{GFF3Metadata}

const _gff3parser_start  = 142
const _gff3parser_first_final  = 142
const _gff3parser_error  = 0
const _gff3parser_en_main  = 142
const __gff3parser_nfa_targs = Int8[ 0, 0 ,  ]
const __gff3parser_nfa_offsets = Int8[ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ,  ]
const __gff3parser_nfa_push_actions = Int8[ 0, 0 ,  ]
const __gff3parser_nfa_pop_trans = Int8[ 0, 0 ,  ]
type GFF3Parser <: AbstractParser
state::Ragel.State
version::VersionNumber
sequence_regions::Vector{Interval{Void}}

function GFF3Parser(input::BufferedInputStream)
	begin
	cs = convert( Int , _gff3parser_start );

end
return new(Ragel.State(cs, input), VersionNumber(0), [])
end
	end

function Intervals.metadatatype(::GFF3Parser)
	return GFF3Metadata
	end

function Base.eltype(::Type{	GFF3Parser})
return GFF3Interval
end

	function 	open(input::BufferedInputStream, ::Type{GFF3})
	return GFF3Parser(input)
end

Ragel.@generate_read_fuction("_gff3parser", GFF3Parser, GFF3Interval,
begin
begin
if ( p == pe  )
	@goto _test_eof

end
if ( cs  == 142 )
	@goto st_case_142
elseif ( cs  == 0 )
	@goto st_case_0
elseif ( cs  == 1 )
	@goto st_case_1
elseif ( cs  == 2 )
	@goto st_case_2
elseif ( cs  == 3 )
	@goto st_case_3
elseif ( cs  == 4 )
	@goto st_case_4
elseif ( cs  == 5 )
	@goto st_case_5
elseif ( cs  == 6 )
	@goto st_case_6
elseif ( cs  == 7 )
	@goto st_case_7
elseif ( cs  == 8 )
	@goto st_case_8
elseif ( cs  == 9 )
	@goto st_case_9
elseif ( cs  == 10 )
	@goto st_case_10
elseif ( cs  == 11 )
	@goto st_case_11
elseif ( cs  == 12 )
	@goto st_case_12
elseif ( cs  == 13 )
	@goto st_case_13
elseif ( cs  == 14 )
	@goto st_case_14
elseif ( cs  == 15 )
	@goto st_case_15
elseif ( cs  == 16 )
	@goto st_case_16
elseif ( cs  == 143 )
	@goto st_case_143
elseif ( cs  == 17 )
	@goto st_case_17
elseif ( cs  == 18 )
	@goto st_case_18
elseif ( cs  == 19 )
	@goto st_case_19
elseif ( cs  == 20 )
	@goto st_case_20
elseif ( cs  == 21 )
	@goto st_case_21
elseif ( cs  == 22 )
	@goto st_case_22
elseif ( cs  == 23 )
	@goto st_case_23
elseif ( cs  == 24 )
	@goto st_case_24
elseif ( cs  == 25 )
	@goto st_case_25
elseif ( cs  == 26 )
	@goto st_case_26
elseif ( cs  == 27 )
	@goto st_case_27
elseif ( cs  == 28 )
	@goto st_case_28
elseif ( cs  == 29 )
	@goto st_case_29
elseif ( cs  == 30 )
	@goto st_case_30
elseif ( cs  == 31 )
	@goto st_case_31
elseif ( cs  == 32 )
	@goto st_case_32
elseif ( cs  == 33 )
	@goto st_case_33
elseif ( cs  == 34 )
	@goto st_case_34
elseif ( cs  == 35 )
	@goto st_case_35
elseif ( cs  == 36 )
	@goto st_case_36
elseif ( cs  == 37 )
	@goto st_case_37
elseif ( cs  == 38 )
	@goto st_case_38
elseif ( cs  == 39 )
	@goto st_case_39
elseif ( cs  == 40 )
	@goto st_case_40
elseif ( cs  == 41 )
	@goto st_case_41
elseif ( cs  == 42 )
	@goto st_case_42
elseif ( cs  == 43 )
	@goto st_case_43
elseif ( cs  == 44 )
	@goto st_case_44
elseif ( cs  == 45 )
	@goto st_case_45
elseif ( cs  == 46 )
	@goto st_case_46
elseif ( cs  == 47 )
	@goto st_case_47
elseif ( cs  == 48 )
	@goto st_case_48
elseif ( cs  == 49 )
	@goto st_case_49
elseif ( cs  == 50 )
	@goto st_case_50
elseif ( cs  == 51 )
	@goto st_case_51
elseif ( cs  == 52 )
	@goto st_case_52
elseif ( cs  == 53 )
	@goto st_case_53
elseif ( cs  == 144 )
	@goto st_case_144
elseif ( cs  == 54 )
	@goto st_case_54
elseif ( cs  == 55 )
	@goto st_case_55
elseif ( cs  == 56 )
	@goto st_case_56
elseif ( cs  == 57 )
	@goto st_case_57
elseif ( cs  == 58 )
	@goto st_case_58
elseif ( cs  == 59 )
	@goto st_case_59
elseif ( cs  == 60 )
	@goto st_case_60
elseif ( cs  == 61 )
	@goto st_case_61
elseif ( cs  == 62 )
	@goto st_case_62
elseif ( cs  == 63 )
	@goto st_case_63
elseif ( cs  == 64 )
	@goto st_case_64
elseif ( cs  == 65 )
	@goto st_case_65
elseif ( cs  == 66 )
	@goto st_case_66
elseif ( cs  == 67 )
	@goto st_case_67
elseif ( cs  == 68 )
	@goto st_case_68
elseif ( cs  == 69 )
	@goto st_case_69
elseif ( cs  == 70 )
	@goto st_case_70
elseif ( cs  == 145 )
	@goto st_case_145
elseif ( cs  == 71 )
	@goto st_case_71
elseif ( cs  == 72 )
	@goto st_case_72
elseif ( cs  == 73 )
	@goto st_case_73
elseif ( cs  == 74 )
	@goto st_case_74
elseif ( cs  == 75 )
	@goto st_case_75
elseif ( cs  == 76 )
	@goto st_case_76
elseif ( cs  == 77 )
	@goto st_case_77
elseif ( cs  == 78 )
	@goto st_case_78
elseif ( cs  == 79 )
	@goto st_case_79
elseif ( cs  == 80 )
	@goto st_case_80
elseif ( cs  == 81 )
	@goto st_case_81
elseif ( cs  == 82 )
	@goto st_case_82
elseif ( cs  == 83 )
	@goto st_case_83
elseif ( cs  == 84 )
	@goto st_case_84
elseif ( cs  == 85 )
	@goto st_case_85
elseif ( cs  == 86 )
	@goto st_case_86
elseif ( cs  == 87 )
	@goto st_case_87
elseif ( cs  == 88 )
	@goto st_case_88
elseif ( cs  == 89 )
	@goto st_case_89
elseif ( cs  == 90 )
	@goto st_case_90
elseif ( cs  == 91 )
	@goto st_case_91
elseif ( cs  == 92 )
	@goto st_case_92
elseif ( cs  == 93 )
	@goto st_case_93
elseif ( cs  == 94 )
	@goto st_case_94
elseif ( cs  == 95 )
	@goto st_case_95
elseif ( cs  == 96 )
	@goto st_case_96
elseif ( cs  == 97 )
	@goto st_case_97
elseif ( cs  == 98 )
	@goto st_case_98
elseif ( cs  == 146 )
	@goto st_case_146
elseif ( cs  == 99 )
	@goto st_case_99
elseif ( cs  == 100 )
	@goto st_case_100
elseif ( cs  == 101 )
	@goto st_case_101
elseif ( cs  == 102 )
	@goto st_case_102
elseif ( cs  == 103 )
	@goto st_case_103
elseif ( cs  == 104 )
	@goto st_case_104
elseif ( cs  == 105 )
	@goto st_case_105
elseif ( cs  == 106 )
	@goto st_case_106
elseif ( cs  == 107 )
	@goto st_case_107
elseif ( cs  == 108 )
	@goto st_case_108
elseif ( cs  == 109 )
	@goto st_case_109
elseif ( cs  == 110 )
	@goto st_case_110
elseif ( cs  == 111 )
	@goto st_case_111
elseif ( cs  == 112 )
	@goto st_case_112
elseif ( cs  == 113 )
	@goto st_case_113
elseif ( cs  == 114 )
	@goto st_case_114
elseif ( cs  == 147 )
	@goto st_case_147
elseif ( cs  == 115 )
	@goto st_case_115
elseif ( cs  == 116 )
	@goto st_case_116
elseif ( cs  == 117 )
	@goto st_case_117
elseif ( cs  == 118 )
	@goto st_case_118
elseif ( cs  == 119 )
	@goto st_case_119
elseif ( cs  == 120 )
	@goto st_case_120
elseif ( cs  == 121 )
	@goto st_case_121
elseif ( cs  == 122 )
	@goto st_case_122
elseif ( cs  == 123 )
	@goto st_case_123
elseif ( cs  == 124 )
	@goto st_case_124
elseif ( cs  == 125 )
	@goto st_case_125
elseif ( cs  == 126 )
	@goto st_case_126
elseif ( cs  == 127 )
	@goto st_case_127
elseif ( cs  == 128 )
	@goto st_case_128
elseif ( cs  == 129 )
	@goto st_case_129
elseif ( cs  == 130 )
	@goto st_case_130
elseif ( cs  == 131 )
	@goto st_case_131
elseif ( cs  == 132 )
	@goto st_case_132
elseif ( cs  == 133 )
	@goto st_case_133
elseif ( cs  == 134 )
	@goto st_case_134
elseif ( cs  == 135 )
	@goto st_case_135
elseif ( cs  == 136 )
	@goto st_case_136
elseif ( cs  == 137 )
	@goto st_case_137
elseif ( cs  == 138 )
	@goto st_case_138
elseif ( cs  == 139 )
	@goto st_case_139
elseif ( cs  == 140 )
	@goto st_case_140
elseif ( cs  == 141 )
	@goto st_case_141
end
@goto st_out
@label st_case_142
if ( (data[1+(p )]) == 9 )
	begin
	@goto ctr209

end
elseif 	( (data[1+(p )]) == 35 )
	begin
	@goto ctr211

end
end
if 	( 32 <= (data[1+(p )])&& (data[1+(p )])<= 126  )
	begin
	@goto ctr210

end

end
begin
	@goto st0

end
@label st_case_0
@label st0
cs = 0;
@goto _out
@label ctr46
begin
Ragel.@copy_from_anchor!(output.seqname)
end
@goto st1
@label ctr209
begin
Ragel.anchor!(state, p)
end
begin
Ragel.@copy_from_anchor!(output.seqname)
end
@goto st1
@label ctr218
begin
directive = Ragel.@ascii_from_anchor!
if startswith(directive, "##gff-version")
# ##gff-version 3.2.1
input.version = VersionNumber(split(directive, r"\s+")[2])
elseif startswith(directive, "##sequence-region")
# ##sequence-region seqid start end
vals = split(directive, r"\s+")
push!(input.sequence_regions,
Interval(vals[2], parse(Int, vals[3]), parse(Int, vals[4])))
else
# TODO: record other directives
end
end
begin
Ragel.anchor!(state, p)
end
begin
Ragel.@copy_from_anchor!(output.seqname)
end
@goto st1
@label st1
p+= 1;
if ( p == pe  )
@goto _test_eof1

end
@label st_case_1
if ( (data[1+(p )])== 9  )
begin
@goto ctr0

end

end
if ( 32 <= (data[1+(p )])&& (data[1+(p )])<= 126  )
begin
@goto ctr2

end

end
begin
@goto st0

end
@label ctr0
begin
Ragel.anchor!(state, p)
end
begin
Ragel.@copy_from_anchor!(output.metadata.source)
end
@goto st2
@label ctr42
begin
Ragel.@copy_from_anchor!(output.metadata.source)
end
@goto st2
@label st2
p+= 1;
if ( p == pe  )
@goto _test_eof2

end
@label st_case_2
if ( (data[1+(p )])== 9  )
begin
@goto ctr3

end

end
if ( 32 <= (data[1+(p )])&& (data[1+(p )])<= 126  )
begin
@goto ctr4

end

end
begin
@goto st0

end
@label ctr3
begin
Ragel.anchor!(state, p)
end
begin
Ragel.@copy_from_anchor!(output.metadata.kind)
end
@goto st3
@label ctr38
begin
Ragel.@copy_from_anchor!(output.metadata.kind)
end
@goto st3
@label st3
p+= 1;
if ( p == pe  )
@goto _test_eof3

end
@label st_case_3
if ( 48 <= (data[1+(p )])&& (data[1+(p )])<= 57  )
begin
@goto ctr5

end

end
begin
@goto st0

end
@label ctr5
begin
Ragel.anchor!(state, p)
end
@goto st4
@label st4
p+= 1;
if ( p == pe  )
@goto _test_eof4

end
@label st_case_4
if ( (data[1+(p )])== 9  )
begin
@goto ctr6

end

end
if ( 48 <= (data[1+(p )])&& (data[1+(p )])<= 57  )
begin
@goto st4

end

end
begin
@goto st0

end
@label ctr6
begin
output.first = Ragel.@int64_from_anchor!
end
@goto st5
@label st5
p+= 1;
if ( p == pe  )
@goto _test_eof5

end
@label st_case_5
if ( 48 <= (data[1+(p )])&& (data[1+(p )])<= 57  )
begin
@goto ctr8

end

end
begin
@goto st0

end
@label ctr8
begin
Ragel.anchor!(state, p)
end
@goto st6
@label st6
p+= 1;
if ( p == pe  )
@goto _test_eof6

end
@label st_case_6
if ( (data[1+(p )])== 9  )
begin
@goto ctr9

end

end
if ( 48 <= (data[1+(p )])&& (data[1+(p )])<= 57  )
begin
@goto st6

end

end
begin
@goto st0

end
@label ctr9
begin
output.last = Ragel.@int64_from_anchor!
end
@goto st7
@label st7
p+= 1;
if ( p == pe  )
@goto _test_eof7

end
@label st_case_7
if ( (data[1+(p )]) == 43 )
begin
@goto ctr11

end
elseif ( (data[1+(p )]) == 45 )
begin
@goto ctr11

end
elseif ( (data[1+(p )]) == 46 )
begin
@goto ctr12

end
end
begin
@goto st0

end
@label ctr11
begin
Ragel.anchor!(state, p)
end
@goto st8
@label st8
p+= 1;
if ( p == pe  )
@goto _test_eof8

end
@label st_case_8
if ( (data[1+(p )])== 46  )
begin
@goto st9

end

end
if ( 48 <= (data[1+(p )])&& (data[1+(p )])<= 57  )
begin
@goto st50

end

end
begin
@goto st0

end
@label st9
p+= 1;
if ( p == pe  )
@goto _test_eof9

end
@label st_case_9
if ( 48 <= (data[1+(p )])&& (data[1+(p )])<= 57  )
begin
@goto st10

end

end
begin
@goto st0

end
@label st10
p+= 1;
if ( p == pe  )
@goto _test_eof10

end
@label st_case_10
if ( (data[1+(p )])== 9  )
begin
@goto ctr16

end

end
if ( 48 <= (data[1+(p )])&& (data[1+(p )])<= 57  )
begin
@goto st10

end

end
begin
@goto st0

end
@label ctr16
begin
output.metadata.score = Nullable(Ragel.@float64_from_anchor!)
end
@goto st11
@label ctr76
begin
output.metadata.score = Nullable{Float64}()
end
@goto st11
@label st11
p+= 1;
if ( p == pe  )
@goto _test_eof11

end
@label st_case_11
if ( (data[1+(p )]) == 43 )
begin
@goto ctr17

end
elseif ( (data[1+(p )]) == 63 )
begin
@goto ctr17

end
end
if ( 45 <= (data[1+(p )])&& (data[1+(p )])<= 46  )
begin
@goto ctr17

end

end
begin
@goto st0

end
@label ctr17
begin
output.strand = convert(Strand, (Ragel.@char))
end
@goto st12
@label st12
p+= 1;
if ( p == pe  )
@goto _test_eof12

end
@label st_case_12
if ( (data[1+(p )])== 9  )
begin
@goto st13

end

end
begin
@goto st0

end
@label st13
p+= 1;
if ( p == pe  )
@goto _test_eof13

end
@label st_case_13
if ( (data[1+(p )])== 46  )
begin
@goto ctr19

end

end
if ( 49 <= (data[1+(p )])&& (data[1+(p )])<= 51  )
begin
@goto ctr20

end

end
begin
@goto st0

end
@label ctr19
begin
Ragel.anchor!(state, p)
end
@goto st14
@label st14
p+= 1;
if ( p == pe  )
@goto _test_eof14

end
@label st_case_14
if ( (data[1+(p )])== 9  )
begin
@goto ctr21

end

end
begin
@goto st0

end
@label ctr21
begin
output.metadata.phase = Nullable{Int}()
end
@goto st15
@label ctr70
begin
output.metadata.phase = Nullable(Ragel.@int64_from_anchor!)
end
@goto st15
@label st15
p+= 1;
if ( p == pe  )
@goto _test_eof15

end
@label st_case_15
if ( (data[1+(p )]) == 10 )
begin
@goto ctr23

end
elseif ( (data[1+(p )]) == 13 )
begin
@goto ctr24

end
end
begin
@goto ctr22

end
@label ctr22
begin
Ragel.anchor!(state, p)
end
@goto st16
@label ctr24
begin
Ragel.anchor!(state, p)
end
begin
Ragel.@copy_from_anchor!(output.metadata.attributes)
end
@goto st16
@label ctr27
begin
Ragel.@copy_from_anchor!(output.metadata.attributes)
end
@goto st16
@label st16
p+= 1;
if ( p == pe  )
@goto _test_eof16

end
@label st_case_16
if ( (data[1+(p )]) == 10 )
begin
@goto ctr26

end
elseif ( (data[1+(p )]) == 13 )
begin
@goto ctr27

end
end
begin
@goto st16

end
@label ctr23
begin
Ragel.anchor!(state, p)
end
begin
Ragel.@copy_from_anchor!(output.metadata.attributes)
end
begin
input.state.linenum += 1
end
@goto st143
@label ctr26
begin
Ragel.@copy_from_anchor!(output.metadata.attributes)
end
begin
input.state.linenum += 1
end
@goto st143
@label ctr29
begin
input.state.linenum += 1
end
@goto st143
@label st143
p+= 1;
if ( p == pe  )
@goto _test_eof143

end
@label st_case_143
if ( (data[1+(p )]) == 9 )
begin
@goto ctr212

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr29

end
elseif ( (data[1+(p )]) == 11 )
begin
@goto st20

end
elseif ( (data[1+(p )]) == 13 )
begin
@goto st21

end
elseif ( (data[1+(p )]) == 32 )
begin
@goto ctr213

end
elseif ( (data[1+(p )]) == 35 )
begin
@goto ctr215

end
end
if ( 33 <= (data[1+(p )])&& (data[1+(p )])<= 126  )
begin
@goto ctr214

end

end
begin
@goto st0

end
@label ctr43
begin
Ragel.@copy_from_anchor!(output.seqname)
end
@goto st17
@label ctr212
begin
yield = true
Ragel.@anchor!
begin
p+= 1;
cs = 17;
@goto _out

end

end
begin
Ragel.anchor!(state, p)
end
begin
Ragel.@copy_from_anchor!(output.seqname)
end
@goto st17
@label ctr221
begin
directive = Ragel.@ascii_from_anchor!
if startswith(directive, "##gff-version")
# ##gff-version 3.2.1
input.version = VersionNumber(split(directive, r"\s+")[2])
elseif startswith(directive, "##sequence-region")
# ##sequence-region seqid start end
vals = split(directive, r"\s+")
push!(input.sequence_regions,
Interval(vals[2], parse(Int, vals[3]), parse(Int, vals[4])))
else
# TODO: record other directives
end
end
begin
yield = true
Ragel.@anchor!
begin
p+= 1;
cs = 17;
@goto _out

end

end
begin
Ragel.anchor!(state, p)
end
begin
Ragel.@copy_from_anchor!(output.seqname)
end
@goto st17
@label st17
p+= 1;
if ( p == pe  )
@goto _test_eof17

end
@label st_case_17
if ( (data[1+(p )]) == 9 )
begin
@goto ctr28

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr29

end
elseif ( (data[1+(p )]) == 11 )
begin
@goto st20

end
elseif ( (data[1+(p )]) == 13 )
begin
@goto st21

end
elseif ( (data[1+(p )]) == 32 )
begin
@goto ctr32

end
end
if ( 33 <= (data[1+(p )])&& (data[1+(p )])<= 126  )
begin
@goto ctr2

end

end
begin
@goto st0

end
@label ctr28
begin
Ragel.anchor!(state, p)
end
begin
Ragel.@copy_from_anchor!(output.metadata.source)
end
@goto st18
@label ctr39
begin
Ragel.@copy_from_anchor!(output.metadata.source)
end
@goto st18
@label st18
p+= 1;
if ( p == pe  )
@goto _test_eof18

end
@label st_case_18
if ( (data[1+(p )]) == 9 )
begin
@goto ctr33

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr29

end
elseif ( (data[1+(p )]) == 11 )
begin
@goto st20

end
elseif ( (data[1+(p )]) == 13 )
begin
@goto st21

end
elseif ( (data[1+(p )]) == 32 )
begin
@goto ctr34

end
end
if ( 33 <= (data[1+(p )])&& (data[1+(p )])<= 126  )
begin
@goto ctr4

end

end
begin
@goto st0

end
@label ctr33
begin
Ragel.anchor!(state, p)
end
begin
Ragel.@copy_from_anchor!(output.metadata.kind)
end
@goto st19
@label ctr35
begin
Ragel.@copy_from_anchor!(output.metadata.kind)
end
@goto st19
@label st19
p+= 1;
if ( p == pe  )
@goto _test_eof19

end
@label st_case_19
if ( (data[1+(p )]) == 10 )
begin
@goto ctr29

end
elseif ( (data[1+(p )]) == 13 )
begin
@goto st21

end
elseif ( (data[1+(p )]) == 32 )
begin
@goto st20

end
end
if ( (data[1+(p )])> 11  )
begin
if ( 48 <= (data[1+(p )])&& (data[1+(p )])<= 57  )
begin
@goto ctr5

end

end

end

elseif ( (data[1+(p )])>= 9  )
begin
@goto st20

end

end
begin
@goto st0

end
@label st20
p+= 1;
if ( p == pe  )
@goto _test_eof20

end
@label st_case_20
if ( (data[1+(p )]) == 10 )
begin
@goto ctr29

end
elseif ( (data[1+(p )]) == 13 )
begin
@goto st21

end
elseif ( (data[1+(p )]) == 32 )
begin
@goto st20

end
end
if ( 9 <= (data[1+(p )])&& (data[1+(p )])<= 11  )
begin
@goto st20

end

end
begin
@goto st0

end
@label st21
p+= 1;
if ( p == pe  )
@goto _test_eof21

end
@label st_case_21
if ( (data[1+(p )])== 10  )
begin
@goto ctr29

end

end
begin
@goto st0

end
@label ctr34
begin
Ragel.anchor!(state, p)
end
@goto st22
@label st22
p+= 1;
if ( p == pe  )
@goto _test_eof22

end
@label st_case_22
if ( (data[1+(p )]) == 9 )
begin
@goto ctr35

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr29

end
elseif ( (data[1+(p )]) == 11 )
begin
@goto st20

end
elseif ( (data[1+(p )]) == 13 )
begin
@goto st21

end
elseif ( (data[1+(p )]) == 32 )
begin
@goto st22

end
end
if ( 33 <= (data[1+(p )])&& (data[1+(p )])<= 126  )
begin
@goto st23

end

end
begin
@goto st0

end
@label ctr4
begin
Ragel.anchor!(state, p)
end
@goto st23
@label st23
p+= 1;
if ( p == pe  )
@goto _test_eof23

end
@label st_case_23
if ( (data[1+(p )])== 9  )
begin
@goto ctr38

end

end
if ( 32 <= (data[1+(p )])&& (data[1+(p )])<= 126  )
begin
@goto st23

end

end
begin
@goto st0

end
@label ctr32
begin
Ragel.anchor!(state, p)
end
@goto st24
@label st24
p+= 1;
if ( p == pe  )
@goto _test_eof24

end
@label st_case_24
if ( (data[1+(p )]) == 9 )
begin
@goto ctr39

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr29

end
elseif ( (data[1+(p )]) == 11 )
begin
@goto st20

end
elseif ( (data[1+(p )]) == 13 )
begin
@goto st21

end
elseif ( (data[1+(p )]) == 32 )
begin
@goto st24

end
end
if ( 33 <= (data[1+(p )])&& (data[1+(p )])<= 126  )
begin
@goto st25

end

end
begin
@goto st0

end
@label ctr2
begin
Ragel.anchor!(state, p)
end
@goto st25
@label st25
p+= 1;
if ( p == pe  )
@goto _test_eof25

end
@label st_case_25
if ( (data[1+(p )])== 9  )
begin
@goto ctr42

end

end
if ( 32 <= (data[1+(p )])&& (data[1+(p )])<= 126  )
begin
@goto st25

end

end
begin
@goto st0

end
@label ctr213
begin
yield = true
Ragel.@anchor!
begin
p+= 1;
cs = 26;
@goto _out

end

end
begin
Ragel.anchor!(state, p)
end
@goto st26
@label ctr222
begin
directive = Ragel.@ascii_from_anchor!
if startswith(directive, "##gff-version")
# ##gff-version 3.2.1
input.version = VersionNumber(split(directive, r"\s+")[2])
elseif startswith(directive, "##sequence-region")
# ##sequence-region seqid start end
vals = split(directive, r"\s+")
push!(input.sequence_regions,
Interval(vals[2], parse(Int, vals[3]), parse(Int, vals[4])))
else
# TODO: record other directives
end
end
begin
yield = true
Ragel.@anchor!
begin
p+= 1;
cs = 26;
@goto _out

end

end
begin
Ragel.anchor!(state, p)
end
@goto st26
@label st26
p+= 1;
if ( p == pe  )
@goto _test_eof26

end
@label st_case_26
if ( (data[1+(p )]) == 9 )
begin
@goto ctr43

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr29

end
elseif ( (data[1+(p )]) == 11 )
begin
@goto st20

end
elseif ( (data[1+(p )]) == 13 )
begin
@goto st21

end
elseif ( (data[1+(p )]) == 32 )
begin
@goto st26

end
end
if ( 33 <= (data[1+(p )])&& (data[1+(p )])<= 126  )
begin
@goto st27

end

end
begin
@goto st0

end
@label ctr210
begin
Ragel.anchor!(state, p)
end
@goto st27
@label ctr214
begin
yield = true
Ragel.@anchor!
begin
p+= 1;
cs = 27;
@goto _out

end

end
begin
Ragel.anchor!(state, p)
end
@goto st27
@label ctr219
begin
directive = Ragel.@ascii_from_anchor!
if startswith(directive, "##gff-version")
# ##gff-version 3.2.1
input.version = VersionNumber(split(directive, r"\s+")[2])
elseif startswith(directive, "##sequence-region")
# ##sequence-region seqid start end
vals = split(directive, r"\s+")
push!(input.sequence_regions,
Interval(vals[2], parse(Int, vals[3]), parse(Int, vals[4])))
else
# TODO: record other directives
end
end
begin
Ragel.anchor!(state, p)
end
@goto st27
@label ctr223
begin
directive = Ragel.@ascii_from_anchor!
if startswith(directive, "##gff-version")
# ##gff-version 3.2.1
input.version = VersionNumber(split(directive, r"\s+")[2])
elseif startswith(directive, "##sequence-region")
# ##sequence-region seqid start end
vals = split(directive, r"\s+")
push!(input.sequence_regions,
Interval(vals[2], parse(Int, vals[3]), parse(Int, vals[4])))
else
# TODO: record other directives
end
end
begin
yield = true
Ragel.@anchor!
begin
p+= 1;
cs = 27;
@goto _out

end

end
begin
Ragel.anchor!(state, p)
end
@goto st27
@label st27
p+= 1;
if ( p == pe  )
@goto _test_eof27

end
@label st_case_27
if ( (data[1+(p )])== 9  )
begin
@goto ctr46

end

end
if ( 32 <= (data[1+(p )])&& (data[1+(p )])<= 126  )
begin
@goto st27

end

end
begin
@goto st0

end
@label ctr215
begin
yield = true
Ragel.@anchor!
begin
p+= 1;
cs = 28;
@goto _out

end

end
begin
Ragel.anchor!(state, p)
end
@goto st28
@label st28
p+= 1;
if ( p == pe  )
@goto _test_eof28

end
@label st_case_28
if ( (data[1+(p )]) == 9 )
begin
@goto ctr48

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr29

end
end
if ( 32 <= (data[1+(p )])&& (data[1+(p )])<= 126  )
begin
@goto st28

end

end
begin
@goto st29

end
@label st29
p+= 1;
if ( p == pe  )
@goto _test_eof29

end
@label st_case_29
if ( (data[1+(p )])== 10  )
begin
@goto ctr29

end

end
begin
@goto st29

end
@label ctr48
begin
Ragel.@copy_from_anchor!(output.seqname)
end
@goto st30
@label st30
p+= 1;
if ( p == pe  )
@goto _test_eof30

end
@label st_case_30
if ( (data[1+(p )]) == 9 )
begin
@goto ctr50

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr29

end
end
if ( 32 <= (data[1+(p )])&& (data[1+(p )])<= 126  )
begin
@goto ctr51

end

end
begin
@goto st29

end
@label ctr50
begin
Ragel.anchor!(state, p)
end
begin
Ragel.@copy_from_anchor!(output.metadata.source)
end
@goto st31
@label ctr74
begin
Ragel.@copy_from_anchor!(output.metadata.source)
end
@goto st31
@label st31
p+= 1;
if ( p == pe  )
@goto _test_eof31

end
@label st_case_31
if ( (data[1+(p )]) == 9 )
begin
@goto ctr52

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr29

end
end
if ( 32 <= (data[1+(p )])&& (data[1+(p )])<= 126  )
begin
@goto ctr53

end

end
begin
@goto st29

end
@label ctr52
begin
Ragel.anchor!(state, p)
end
begin
Ragel.@copy_from_anchor!(output.metadata.kind)
end
@goto st32
@label ctr72
begin
Ragel.@copy_from_anchor!(output.metadata.kind)
end
@goto st32
@label st32
p+= 1;
if ( p == pe  )
@goto _test_eof32

end
@label st_case_32
if ( (data[1+(p )])== 10  )
begin
@goto ctr29

end

end
if ( 48 <= (data[1+(p )])&& (data[1+(p )])<= 57  )
begin
@goto ctr54

end

end
begin
@goto st29

end
@label ctr54
begin
Ragel.anchor!(state, p)
end
@goto st33
@label st33
p+= 1;
if ( p == pe  )
@goto _test_eof33

end
@label st_case_33
if ( (data[1+(p )]) == 9 )
begin
@goto ctr55

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr29

end
end
if ( 48 <= (data[1+(p )])&& (data[1+(p )])<= 57  )
begin
@goto st33

end

end
begin
@goto st29

end
@label ctr55
begin
output.first = Ragel.@int64_from_anchor!
end
@goto st34
@label st34
p+= 1;
if ( p == pe  )
@goto _test_eof34

end
@label st_case_34
if ( (data[1+(p )])== 10  )
begin
@goto ctr29

end

end
if ( 48 <= (data[1+(p )])&& (data[1+(p )])<= 57  )
begin
@goto ctr57

end

end
begin
@goto st29

end
@label ctr57
begin
Ragel.anchor!(state, p)
end
@goto st35
@label st35
p+= 1;
if ( p == pe  )
@goto _test_eof35

end
@label st_case_35
if ( (data[1+(p )]) == 9 )
begin
@goto ctr58

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr29

end
end
if ( 48 <= (data[1+(p )])&& (data[1+(p )])<= 57  )
begin
@goto st35

end

end
begin
@goto st29

end
@label ctr58
begin
output.last = Ragel.@int64_from_anchor!
end
@goto st36
@label st36
p+= 1;
if ( p == pe  )
@goto _test_eof36

end
@label st_case_36
if ( (data[1+(p )]) == 10 )
begin
@goto ctr29

end
elseif ( (data[1+(p )]) == 43 )
begin
@goto ctr60

end
elseif ( (data[1+(p )]) == 45 )
begin
@goto ctr60

end
elseif ( (data[1+(p )]) == 46 )
begin
@goto ctr61

end
end
begin
@goto st29

end
@label ctr60
begin
Ragel.anchor!(state, p)
end
@goto st37
@label st37
p+= 1;
if ( p == pe  )
@goto _test_eof37

end
@label st_case_37
if ( (data[1+(p )]) == 10 )
begin
@goto ctr29

end
elseif ( (data[1+(p )]) == 46 )
begin
@goto st38

end
end
if ( 48 <= (data[1+(p )])&& (data[1+(p )])<= 57  )
begin
@goto st45

end

end
begin
@goto st29

end
@label st38
p+= 1;
if ( p == pe  )
@goto _test_eof38

end
@label st_case_38
if ( (data[1+(p )])== 10  )
begin
@goto ctr29

end

end
if ( 48 <= (data[1+(p )])&& (data[1+(p )])<= 57  )
begin
@goto st39

end

end
begin
@goto st29

end
@label st39
p+= 1;
if ( p == pe  )
@goto _test_eof39

end
@label st_case_39
if ( (data[1+(p )]) == 9 )
begin
@goto ctr65

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr29

end
end
if ( 48 <= (data[1+(p )])&& (data[1+(p )])<= 57  )
begin
@goto st39

end

end
begin
@goto st29

end
@label ctr65
begin
output.metadata.score = Nullable(Ragel.@float64_from_anchor!)
end
@goto st40
@label ctr71
begin
output.metadata.score = Nullable{Float64}()
end
@goto st40
@label st40
p+= 1;
if ( p == pe  )
@goto _test_eof40

end
@label st_case_40
if ( (data[1+(p )]) == 10 )
begin
@goto ctr29

end
elseif ( (data[1+(p )]) == 43 )
begin
@goto ctr66

end
elseif ( (data[1+(p )]) == 63 )
begin
@goto ctr66

end
end
if ( 45 <= (data[1+(p )])&& (data[1+(p )])<= 46  )
begin
@goto ctr66

end

end
begin
@goto st29

end
@label ctr66
begin
output.strand = convert(Strand, (Ragel.@char))
end
@goto st41
@label st41
p+= 1;
if ( p == pe  )
@goto _test_eof41

end
@label st_case_41
if ( (data[1+(p )]) == 9 )
begin
@goto st42

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr29

end
end
begin
@goto st29

end
@label st42
p+= 1;
if ( p == pe  )
@goto _test_eof42

end
@label st_case_42
if ( (data[1+(p )]) == 10 )
begin
@goto ctr29

end
elseif ( (data[1+(p )]) == 46 )
begin
@goto ctr68

end
end
if ( 49 <= (data[1+(p )])&& (data[1+(p )])<= 51  )
begin
@goto ctr69

end

end
begin
@goto st29

end
@label ctr68
begin
Ragel.anchor!(state, p)
end
@goto st43
@label st43
p+= 1;
if ( p == pe  )
@goto _test_eof43

end
@label st_case_43
if ( (data[1+(p )]) == 9 )
begin
@goto ctr21

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr29

end
end
begin
@goto st29

end
@label ctr69
begin
Ragel.anchor!(state, p)
end
@goto st44
@label st44
p+= 1;
if ( p == pe  )
@goto _test_eof44

end
@label st_case_44
if ( (data[1+(p )]) == 9 )
begin
@goto ctr70

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr29

end
end
begin
@goto st29

end
@label st45
p+= 1;
if ( p == pe  )
@goto _test_eof45

end
@label st_case_45
if ( (data[1+(p )]) == 9 )
begin
@goto ctr65

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr29

end
elseif ( (data[1+(p )]) == 46 )
begin
@goto st38

end
end
if ( 48 <= (data[1+(p )])&& (data[1+(p )])<= 57  )
begin
@goto st45

end

end
begin
@goto st29

end
@label ctr61
begin
Ragel.anchor!(state, p)
end
@goto st46
@label st46
p+= 1;
if ( p == pe  )
@goto _test_eof46

end
@label st_case_46
if ( (data[1+(p )]) == 9 )
begin
@goto ctr71

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr29

end
end
begin
@goto st29

end
@label ctr53
begin
Ragel.anchor!(state, p)
end
@goto st47
@label st47
p+= 1;
if ( p == pe  )
@goto _test_eof47

end
@label st_case_47
if ( (data[1+(p )]) == 9 )
begin
@goto ctr72

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr29

end
end
if ( 32 <= (data[1+(p )])&& (data[1+(p )])<= 126  )
begin
@goto st47

end

end
begin
@goto st29

end
@label ctr51
begin
Ragel.anchor!(state, p)
end
@goto st48
@label st48
p+= 1;
if ( p == pe  )
@goto _test_eof48

end
@label st_case_48
if ( (data[1+(p )]) == 9 )
begin
@goto ctr74

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr29

end
end
if ( 32 <= (data[1+(p )])&& (data[1+(p )])<= 126  )
begin
@goto st48

end

end
begin
@goto st29

end
@label ctr20
begin
Ragel.anchor!(state, p)
end
@goto st49
@label st49
p+= 1;
if ( p == pe  )
@goto _test_eof49

end
@label st_case_49
if ( (data[1+(p )])== 9  )
begin
@goto ctr70

end

end
begin
@goto st0

end
@label st50
p+= 1;
if ( p == pe  )
@goto _test_eof50

end
@label st_case_50
if ( (data[1+(p )]) == 9 )
begin
@goto ctr16

end
elseif ( (data[1+(p )]) == 46 )
begin
@goto st9

end
end
if ( 48 <= (data[1+(p )])&& (data[1+(p )])<= 57  )
begin
@goto st50

end

end
begin
@goto st0

end
@label ctr12
begin
Ragel.anchor!(state, p)
end
@goto st51
@label st51
p+= 1;
if ( p == pe  )
@goto _test_eof51

end
@label st_case_51
if ( (data[1+(p )])== 9  )
begin
@goto ctr76

end

end
begin
@goto st0

end
@label ctr211
begin
Ragel.anchor!(state, p)
end
@goto st52
@label ctr220
begin
directive = Ragel.@ascii_from_anchor!
if startswith(directive, "##gff-version")
# ##gff-version 3.2.1
input.version = VersionNumber(split(directive, r"\s+")[2])
elseif startswith(directive, "##sequence-region")
# ##sequence-region seqid start end
vals = split(directive, r"\s+")
push!(input.sequence_regions,
Interval(vals[2], parse(Int, vals[3]), parse(Int, vals[4])))
else
# TODO: record other directives
end
end
begin
Ragel.anchor!(state, p)
end
@goto st52
@label st52
p+= 1;
if ( p == pe  )
@goto _test_eof52

end
@label st_case_52
if ( (data[1+(p )]) == 9 )
begin
@goto ctr78

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr79

end
elseif ( (data[1+(p )]) == 35 )
begin
@goto st97

end
end
if ( 32 <= (data[1+(p )])&& (data[1+(p )])<= 126  )
begin
@goto st54

end

end
begin
@goto st53

end
@label st53
p+= 1;
if ( p == pe  )
@goto _test_eof53

end
@label st_case_53
if ( (data[1+(p )])== 10  )
begin
@goto ctr79

end

end
begin
@goto st53

end
@label ctr79
begin
input.state.linenum += 1
end
@goto st144
@label st144
p+= 1;
if ( p == pe  )
@goto _test_eof144

end
@label st_case_144
if ( (data[1+(p )]) == 9 )
begin
@goto ctr209

end
elseif ( (data[1+(p )]) == 35 )
begin
@goto ctr216

end
end
if ( 32 <= (data[1+(p )])&& (data[1+(p )])<= 126  )
begin
@goto ctr210

end

end
begin
@goto st0

end
@label ctr216
begin
Ragel.anchor!(state, p)
end
@goto st54
@label st54
p+= 1;
if ( p == pe  )
@goto _test_eof54

end
@label st_case_54
if ( (data[1+(p )]) == 9 )
begin
@goto ctr78

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr79

end
end
if ( 32 <= (data[1+(p )])&& (data[1+(p )])<= 126  )
begin
@goto st54

end

end
begin
@goto st53

end
@label ctr78
begin
Ragel.@copy_from_anchor!(output.seqname)
end
@goto st55
@label st55
p+= 1;
if ( p == pe  )
@goto _test_eof55

end
@label st_case_55
if ( (data[1+(p )]) == 9 )
begin
@goto ctr82

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr79

end
end
if ( 32 <= (data[1+(p )])&& (data[1+(p )])<= 126  )
begin
@goto ctr83

end

end
begin
@goto st53

end
@label ctr82
begin
Ragel.anchor!(state, p)
end
begin
Ragel.@copy_from_anchor!(output.metadata.source)
end
@goto st56
@label ctr142
begin
Ragel.@copy_from_anchor!(output.metadata.source)
end
@goto st56
@label st56
p+= 1;
if ( p == pe  )
@goto _test_eof56

end
@label st_case_56
if ( (data[1+(p )]) == 9 )
begin
@goto ctr84

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr79

end
end
if ( 32 <= (data[1+(p )])&& (data[1+(p )])<= 126  )
begin
@goto ctr85

end

end
begin
@goto st53

end
@label ctr84
begin
Ragel.anchor!(state, p)
end
begin
Ragel.@copy_from_anchor!(output.metadata.kind)
end
@goto st57
@label ctr140
begin
Ragel.@copy_from_anchor!(output.metadata.kind)
end
@goto st57
@label st57
p+= 1;
if ( p == pe  )
@goto _test_eof57

end
@label st_case_57
if ( (data[1+(p )])== 10  )
begin
@goto ctr79

end

end
if ( 48 <= (data[1+(p )])&& (data[1+(p )])<= 57  )
begin
@goto ctr86

end

end
begin
@goto st53

end
@label ctr86
begin
Ragel.anchor!(state, p)
end
@goto st58
@label st58
p+= 1;
if ( p == pe  )
@goto _test_eof58

end
@label st_case_58
if ( (data[1+(p )]) == 9 )
begin
@goto ctr87

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr79

end
end
if ( 48 <= (data[1+(p )])&& (data[1+(p )])<= 57  )
begin
@goto st58

end

end
begin
@goto st53

end
@label ctr87
begin
output.first = Ragel.@int64_from_anchor!
end
@goto st59
@label st59
p+= 1;
if ( p == pe  )
@goto _test_eof59

end
@label st_case_59
if ( (data[1+(p )])== 10  )
begin
@goto ctr79

end

end
if ( 48 <= (data[1+(p )])&& (data[1+(p )])<= 57  )
begin
@goto ctr89

end

end
begin
@goto st53

end
@label ctr89
begin
Ragel.anchor!(state, p)
end
@goto st60
@label st60
p+= 1;
if ( p == pe  )
@goto _test_eof60

end
@label st_case_60
if ( (data[1+(p )]) == 9 )
begin
@goto ctr90

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr79

end
end
if ( 48 <= (data[1+(p )])&& (data[1+(p )])<= 57  )
begin
@goto st60

end

end
begin
@goto st53

end
@label ctr90
begin
output.last = Ragel.@int64_from_anchor!
end
@goto st61
@label st61
p+= 1;
if ( p == pe  )
@goto _test_eof61

end
@label st_case_61
if ( (data[1+(p )]) == 10 )
begin
@goto ctr79

end
elseif ( (data[1+(p )]) == 43 )
begin
@goto ctr92

end
elseif ( (data[1+(p )]) == 45 )
begin
@goto ctr92

end
elseif ( (data[1+(p )]) == 46 )
begin
@goto ctr93

end
end
begin
@goto st53

end
@label ctr92
begin
Ragel.anchor!(state, p)
end
@goto st62
@label st62
p+= 1;
if ( p == pe  )
@goto _test_eof62

end
@label st_case_62
if ( (data[1+(p )]) == 10 )
begin
@goto ctr79

end
elseif ( (data[1+(p )]) == 46 )
begin
@goto st63

end
end
if ( 48 <= (data[1+(p )])&& (data[1+(p )])<= 57  )
begin
@goto st93

end

end
begin
@goto st53

end
@label st63
p+= 1;
if ( p == pe  )
@goto _test_eof63

end
@label st_case_63
if ( (data[1+(p )])== 10  )
begin
@goto ctr79

end

end
if ( 48 <= (data[1+(p )])&& (data[1+(p )])<= 57  )
begin
@goto st64

end

end
begin
@goto st53

end
@label st64
p+= 1;
if ( p == pe  )
@goto _test_eof64

end
@label st_case_64
if ( (data[1+(p )]) == 9 )
begin
@goto ctr97

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr79

end
end
if ( 48 <= (data[1+(p )])&& (data[1+(p )])<= 57  )
begin
@goto st64

end

end
begin
@goto st53

end
@label ctr97
begin
output.metadata.score = Nullable(Ragel.@float64_from_anchor!)
end
@goto st65
@label ctr139
begin
output.metadata.score = Nullable{Float64}()
end
@goto st65
@label st65
p+= 1;
if ( p == pe  )
@goto _test_eof65

end
@label st_case_65
if ( (data[1+(p )]) == 10 )
begin
@goto ctr79

end
elseif ( (data[1+(p )]) == 43 )
begin
@goto ctr98

end
elseif ( (data[1+(p )]) == 63 )
begin
@goto ctr98

end
end
if ( 45 <= (data[1+(p )])&& (data[1+(p )])<= 46  )
begin
@goto ctr98

end

end
begin
@goto st53

end
@label ctr98
begin
output.strand = convert(Strand, (Ragel.@char))
end
@goto st66
@label st66
p+= 1;
if ( p == pe  )
@goto _test_eof66

end
@label st_case_66
if ( (data[1+(p )]) == 9 )
begin
@goto st67

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr79

end
end
begin
@goto st53

end
@label st67
p+= 1;
if ( p == pe  )
@goto _test_eof67

end
@label st_case_67
if ( (data[1+(p )]) == 10 )
begin
@goto ctr79

end
elseif ( (data[1+(p )]) == 46 )
begin
@goto ctr100

end
end
if ( 49 <= (data[1+(p )])&& (data[1+(p )])<= 51  )
begin
@goto ctr101

end

end
begin
@goto st53

end
@label ctr100
begin
Ragel.anchor!(state, p)
end
@goto st68
@label st68
p+= 1;
if ( p == pe  )
@goto _test_eof68

end
@label st_case_68
if ( (data[1+(p )]) == 9 )
begin
@goto ctr102

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr79

end
end
begin
@goto st53

end
@label ctr102
begin
output.metadata.phase = Nullable{Int}()
end
@goto st69
@label ctr133
begin
output.metadata.phase = Nullable(Ragel.@int64_from_anchor!)
end
@goto st69
@label st69
p+= 1;
if ( p == pe  )
@goto _test_eof69

end
@label st_case_69
if ( (data[1+(p )]) == 10 )
begin
@goto ctr104

end
elseif ( (data[1+(p )]) == 13 )
begin
@goto ctr105

end
end
begin
@goto ctr103

end
@label ctr103
begin
Ragel.anchor!(state, p)
end
@goto st70
@label ctr105
begin
Ragel.anchor!(state, p)
end
begin
Ragel.@copy_from_anchor!(output.metadata.attributes)
end
@goto st70
@label ctr108
begin
Ragel.@copy_from_anchor!(output.metadata.attributes)
end
@goto st70
@label st70
p+= 1;
if ( p == pe  )
@goto _test_eof70

end
@label st_case_70
if ( (data[1+(p )]) == 10 )
begin
@goto ctr107

end
elseif ( (data[1+(p )]) == 13 )
begin
@goto ctr108

end
end
begin
@goto st70

end
@label ctr111
begin
input.state.linenum += 1
end
@goto st145
@label ctr104
begin
input.state.linenum += 1
end
begin
Ragel.anchor!(state, p)
end
begin
Ragel.@copy_from_anchor!(output.metadata.attributes)
end
@goto st145
@label ctr107
begin
input.state.linenum += 1
end
begin
Ragel.@copy_from_anchor!(output.metadata.attributes)
end
@goto st145
@label st145
p+= 1;
if ( p == pe  )
@goto _test_eof145

end
@label st_case_145
if ( (data[1+(p )]) == 9 )
begin
@goto ctr212

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr29

end
elseif ( (data[1+(p )]) == 11 )
begin
@goto st20

end
elseif ( (data[1+(p )]) == 13 )
begin
@goto st21

end
elseif ( (data[1+(p )]) == 32 )
begin
@goto ctr213

end
elseif ( (data[1+(p )]) == 35 )
begin
@goto ctr217

end
end
if ( 33 <= (data[1+(p )])&& (data[1+(p )])<= 126  )
begin
@goto ctr214

end

end
begin
@goto st0

end
@label ctr217
begin
yield = true
Ragel.@anchor!
begin
p+= 1;
cs = 71;
@goto _out

end

end
begin
Ragel.anchor!(state, p)
end
@goto st71
@label st71
p+= 1;
if ( p == pe  )
@goto _test_eof71

end
@label st_case_71
if ( (data[1+(p )]) == 9 )
begin
@goto ctr110

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr111

end
end
if ( 32 <= (data[1+(p )])&& (data[1+(p )])<= 126  )
begin
@goto st71

end

end
begin
@goto st72

end
@label st72
p+= 1;
if ( p == pe  )
@goto _test_eof72

end
@label st_case_72
if ( (data[1+(p )])== 10  )
begin
@goto ctr111

end

end
begin
@goto st72

end
@label ctr110
begin
Ragel.@copy_from_anchor!(output.seqname)
end
@goto st73
@label st73
p+= 1;
if ( p == pe  )
@goto _test_eof73

end
@label st_case_73
if ( (data[1+(p )]) == 9 )
begin
@goto ctr113

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr111

end
end
if ( 32 <= (data[1+(p )])&& (data[1+(p )])<= 126  )
begin
@goto ctr114

end

end
begin
@goto st72

end
@label ctr113
begin
Ragel.anchor!(state, p)
end
begin
Ragel.@copy_from_anchor!(output.metadata.source)
end
@goto st74
@label ctr137
begin
Ragel.@copy_from_anchor!(output.metadata.source)
end
@goto st74
@label st74
p+= 1;
if ( p == pe  )
@goto _test_eof74

end
@label st_case_74
if ( (data[1+(p )]) == 9 )
begin
@goto ctr115

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr111

end
end
if ( 32 <= (data[1+(p )])&& (data[1+(p )])<= 126  )
begin
@goto ctr116

end

end
begin
@goto st72

end
@label ctr115
begin
Ragel.anchor!(state, p)
end
begin
Ragel.@copy_from_anchor!(output.metadata.kind)
end
@goto st75
@label ctr135
begin
Ragel.@copy_from_anchor!(output.metadata.kind)
end
@goto st75
@label st75
p+= 1;
if ( p == pe  )
@goto _test_eof75

end
@label st_case_75
if ( (data[1+(p )])== 10  )
begin
@goto ctr111

end

end
if ( 48 <= (data[1+(p )])&& (data[1+(p )])<= 57  )
begin
@goto ctr117

end

end
begin
@goto st72

end
@label ctr117
begin
Ragel.anchor!(state, p)
end
@goto st76
@label st76
p+= 1;
if ( p == pe  )
@goto _test_eof76

end
@label st_case_76
if ( (data[1+(p )]) == 9 )
begin
@goto ctr118

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr111

end
end
if ( 48 <= (data[1+(p )])&& (data[1+(p )])<= 57  )
begin
@goto st76

end

end
begin
@goto st72

end
@label ctr118
begin
output.first = Ragel.@int64_from_anchor!
end
@goto st77
@label st77
p+= 1;
if ( p == pe  )
@goto _test_eof77

end
@label st_case_77
if ( (data[1+(p )])== 10  )
begin
@goto ctr111

end

end
if ( 48 <= (data[1+(p )])&& (data[1+(p )])<= 57  )
begin
@goto ctr120

end

end
begin
@goto st72

end
@label ctr120
begin
Ragel.anchor!(state, p)
end
@goto st78
@label st78
p+= 1;
if ( p == pe  )
@goto _test_eof78

end
@label st_case_78
if ( (data[1+(p )]) == 9 )
begin
@goto ctr121

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr111

end
end
if ( 48 <= (data[1+(p )])&& (data[1+(p )])<= 57  )
begin
@goto st78

end

end
begin
@goto st72

end
@label ctr121
begin
output.last = Ragel.@int64_from_anchor!
end
@goto st79
@label st79
p+= 1;
if ( p == pe  )
@goto _test_eof79

end
@label st_case_79
if ( (data[1+(p )]) == 10 )
begin
@goto ctr111

end
elseif ( (data[1+(p )]) == 43 )
begin
@goto ctr123

end
elseif ( (data[1+(p )]) == 45 )
begin
@goto ctr123

end
elseif ( (data[1+(p )]) == 46 )
begin
@goto ctr124

end
end
begin
@goto st72

end
@label ctr123
begin
Ragel.anchor!(state, p)
end
@goto st80
@label st80
p+= 1;
if ( p == pe  )
@goto _test_eof80

end
@label st_case_80
if ( (data[1+(p )]) == 10 )
begin
@goto ctr111

end
elseif ( (data[1+(p )]) == 46 )
begin
@goto st81

end
end
if ( 48 <= (data[1+(p )])&& (data[1+(p )])<= 57  )
begin
@goto st88

end

end
begin
@goto st72

end
@label st81
p+= 1;
if ( p == pe  )
@goto _test_eof81

end
@label st_case_81
if ( (data[1+(p )])== 10  )
begin
@goto ctr111

end

end
if ( 48 <= (data[1+(p )])&& (data[1+(p )])<= 57  )
begin
@goto st82

end

end
begin
@goto st72

end
@label st82
p+= 1;
if ( p == pe  )
@goto _test_eof82

end
@label st_case_82
if ( (data[1+(p )]) == 9 )
begin
@goto ctr128

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr111

end
end
if ( 48 <= (data[1+(p )])&& (data[1+(p )])<= 57  )
begin
@goto st82

end

end
begin
@goto st72

end
@label ctr128
begin
output.metadata.score = Nullable(Ragel.@float64_from_anchor!)
end
@goto st83
@label ctr134
begin
output.metadata.score = Nullable{Float64}()
end
@goto st83
@label st83
p+= 1;
if ( p == pe  )
@goto _test_eof83

end
@label st_case_83
if ( (data[1+(p )]) == 10 )
begin
@goto ctr111

end
elseif ( (data[1+(p )]) == 43 )
begin
@goto ctr129

end
elseif ( (data[1+(p )]) == 63 )
begin
@goto ctr129

end
end
if ( 45 <= (data[1+(p )])&& (data[1+(p )])<= 46  )
begin
@goto ctr129

end

end
begin
@goto st72

end
@label ctr129
begin
output.strand = convert(Strand, (Ragel.@char))
end
@goto st84
@label st84
p+= 1;
if ( p == pe  )
@goto _test_eof84

end
@label st_case_84
if ( (data[1+(p )]) == 9 )
begin
@goto st85

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr111

end
end
begin
@goto st72

end
@label st85
p+= 1;
if ( p == pe  )
@goto _test_eof85

end
@label st_case_85
if ( (data[1+(p )]) == 10 )
begin
@goto ctr111

end
elseif ( (data[1+(p )]) == 46 )
begin
@goto ctr131

end
end
if ( 49 <= (data[1+(p )])&& (data[1+(p )])<= 51  )
begin
@goto ctr132

end

end
begin
@goto st72

end
@label ctr131
begin
Ragel.anchor!(state, p)
end
@goto st86
@label st86
p+= 1;
if ( p == pe  )
@goto _test_eof86

end
@label st_case_86
if ( (data[1+(p )]) == 9 )
begin
@goto ctr102

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr111

end
end
begin
@goto st72

end
@label ctr132
begin
Ragel.anchor!(state, p)
end
@goto st87
@label st87
p+= 1;
if ( p == pe  )
@goto _test_eof87

end
@label st_case_87
if ( (data[1+(p )]) == 9 )
begin
@goto ctr133

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr111

end
end
begin
@goto st72

end
@label st88
p+= 1;
if ( p == pe  )
@goto _test_eof88

end
@label st_case_88
if ( (data[1+(p )]) == 9 )
begin
@goto ctr128

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr111

end
elseif ( (data[1+(p )]) == 46 )
begin
@goto st81

end
end
if ( 48 <= (data[1+(p )])&& (data[1+(p )])<= 57  )
begin
@goto st88

end

end
begin
@goto st72

end
@label ctr124
begin
Ragel.anchor!(state, p)
end
@goto st89
@label st89
p+= 1;
if ( p == pe  )
@goto _test_eof89

end
@label st_case_89
if ( (data[1+(p )]) == 9 )
begin
@goto ctr134

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr111

end
end
begin
@goto st72

end
@label ctr116
begin
Ragel.anchor!(state, p)
end
@goto st90
@label st90
p+= 1;
if ( p == pe  )
@goto _test_eof90

end
@label st_case_90
if ( (data[1+(p )]) == 9 )
begin
@goto ctr135

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr111

end
end
if ( 32 <= (data[1+(p )])&& (data[1+(p )])<= 126  )
begin
@goto st90

end

end
begin
@goto st72

end
@label ctr114
begin
Ragel.anchor!(state, p)
end
@goto st91
@label st91
p+= 1;
if ( p == pe  )
@goto _test_eof91

end
@label st_case_91
if ( (data[1+(p )]) == 9 )
begin
@goto ctr137

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr111

end
end
if ( 32 <= (data[1+(p )])&& (data[1+(p )])<= 126  )
begin
@goto st91

end

end
begin
@goto st72

end
@label ctr101
begin
Ragel.anchor!(state, p)
end
@goto st92
@label st92
p+= 1;
if ( p == pe  )
@goto _test_eof92

end
@label st_case_92
if ( (data[1+(p )]) == 9 )
begin
@goto ctr133

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr79

end
end
begin
@goto st53

end
@label st93
p+= 1;
if ( p == pe  )
@goto _test_eof93

end
@label st_case_93
if ( (data[1+(p )]) == 9 )
begin
@goto ctr97

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr79

end
elseif ( (data[1+(p )]) == 46 )
begin
@goto st63

end
end
if ( 48 <= (data[1+(p )])&& (data[1+(p )])<= 57  )
begin
@goto st93

end

end
begin
@goto st53

end
@label ctr93
begin
Ragel.anchor!(state, p)
end
@goto st94
@label st94
p+= 1;
if ( p == pe  )
@goto _test_eof94

end
@label st_case_94
if ( (data[1+(p )]) == 9 )
begin
@goto ctr139

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr79

end
end
begin
@goto st53

end
@label ctr85
begin
Ragel.anchor!(state, p)
end
@goto st95
@label st95
p+= 1;
if ( p == pe  )
@goto _test_eof95

end
@label st_case_95
if ( (data[1+(p )]) == 9 )
begin
@goto ctr140

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr79

end
end
if ( 32 <= (data[1+(p )])&& (data[1+(p )])<= 126  )
begin
@goto st95

end

end
begin
@goto st53

end
@label ctr83
begin
Ragel.anchor!(state, p)
end
@goto st96
@label st96
p+= 1;
if ( p == pe  )
@goto _test_eof96

end
@label st_case_96
if ( (data[1+(p )]) == 9 )
begin
@goto ctr142

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr79

end
end
if ( 32 <= (data[1+(p )])&& (data[1+(p )])<= 126  )
begin
@goto st96

end

end
begin
@goto st53

end
@label st97
p+= 1;
if ( p == pe  )
@goto _test_eof97

end
@label st_case_97
if ( (data[1+(p )]) == 9 )
begin
@goto ctr145

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr146

end
end
if ( 32 <= (data[1+(p )])&& (data[1+(p )])<= 126  )
begin
@goto st97

end

end
begin
@goto st98

end
@label st98
p+= 1;
if ( p == pe  )
@goto _test_eof98

end
@label st_case_98
if ( (data[1+(p )])== 10  )
begin
@goto ctr146

end

end
begin
@goto st98

end
@label ctr146
begin
input.state.linenum += 1
end
@goto st146
@label st146
p+= 1;
if ( p == pe  )
@goto _test_eof146

end
@label st_case_146
if ( (data[1+(p )]) == 9 )
begin
@goto ctr218

end
elseif ( (data[1+(p )]) == 35 )
begin
@goto ctr220

end
end
if ( 32 <= (data[1+(p )])&& (data[1+(p )])<= 126  )
begin
@goto ctr219

end

end
begin
@goto st0

end
@label ctr145
begin
Ragel.@copy_from_anchor!(output.seqname)
end
@goto st99
@label st99
p+= 1;
if ( p == pe  )
@goto _test_eof99

end
@label st_case_99
if ( (data[1+(p )]) == 9 )
begin
@goto ctr147

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr146

end
end
if ( 32 <= (data[1+(p )])&& (data[1+(p )])<= 126  )
begin
@goto ctr148

end

end
begin
@goto st98

end
@label ctr147
begin
Ragel.anchor!(state, p)
end
begin
Ragel.@copy_from_anchor!(output.metadata.source)
end
@goto st100
@label ctr207
begin
Ragel.@copy_from_anchor!(output.metadata.source)
end
@goto st100
@label st100
p+= 1;
if ( p == pe  )
@goto _test_eof100

end
@label st_case_100
if ( (data[1+(p )]) == 9 )
begin
@goto ctr149

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr146

end
end
if ( 32 <= (data[1+(p )])&& (data[1+(p )])<= 126  )
begin
@goto ctr150

end

end
begin
@goto st98

end
@label ctr149
begin
Ragel.anchor!(state, p)
end
begin
Ragel.@copy_from_anchor!(output.metadata.kind)
end
@goto st101
@label ctr205
begin
Ragel.@copy_from_anchor!(output.metadata.kind)
end
@goto st101
@label st101
p+= 1;
if ( p == pe  )
@goto _test_eof101

end
@label st_case_101
if ( (data[1+(p )])== 10  )
begin
@goto ctr146

end

end
if ( 48 <= (data[1+(p )])&& (data[1+(p )])<= 57  )
begin
@goto ctr151

end

end
begin
@goto st98

end
@label ctr151
begin
Ragel.anchor!(state, p)
end
@goto st102
@label st102
p+= 1;
if ( p == pe  )
@goto _test_eof102

end
@label st_case_102
if ( (data[1+(p )]) == 9 )
begin
@goto ctr152

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr146

end
end
if ( 48 <= (data[1+(p )])&& (data[1+(p )])<= 57  )
begin
@goto st102

end

end
begin
@goto st98

end
@label ctr152
begin
output.first = Ragel.@int64_from_anchor!
end
@goto st103
@label st103
p+= 1;
if ( p == pe  )
@goto _test_eof103

end
@label st_case_103
if ( (data[1+(p )])== 10  )
begin
@goto ctr146

end

end
if ( 48 <= (data[1+(p )])&& (data[1+(p )])<= 57  )
begin
@goto ctr154

end

end
begin
@goto st98

end
@label ctr154
begin
Ragel.anchor!(state, p)
end
@goto st104
@label st104
p+= 1;
if ( p == pe  )
@goto _test_eof104

end
@label st_case_104
if ( (data[1+(p )]) == 9 )
begin
@goto ctr155

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr146

end
end
if ( 48 <= (data[1+(p )])&& (data[1+(p )])<= 57  )
begin
@goto st104

end

end
begin
@goto st98

end
@label ctr155
begin
output.last = Ragel.@int64_from_anchor!
end
@goto st105
@label st105
p+= 1;
if ( p == pe  )
@goto _test_eof105

end
@label st_case_105
if ( (data[1+(p )]) == 10 )
begin
@goto ctr146

end
elseif ( (data[1+(p )]) == 43 )
begin
@goto ctr157

end
elseif ( (data[1+(p )]) == 45 )
begin
@goto ctr157

end
elseif ( (data[1+(p )]) == 46 )
begin
@goto ctr158

end
end
begin
@goto st98

end
@label ctr157
begin
Ragel.anchor!(state, p)
end
@goto st106
@label st106
p+= 1;
if ( p == pe  )
@goto _test_eof106

end
@label st_case_106
if ( (data[1+(p )]) == 10 )
begin
@goto ctr146

end
elseif ( (data[1+(p )]) == 46 )
begin
@goto st107

end
end
if ( 48 <= (data[1+(p )])&& (data[1+(p )])<= 57  )
begin
@goto st138

end

end
begin
@goto st98

end
@label st107
p+= 1;
if ( p == pe  )
@goto _test_eof107

end
@label st_case_107
if ( (data[1+(p )])== 10  )
begin
@goto ctr146

end

end
if ( 48 <= (data[1+(p )])&& (data[1+(p )])<= 57  )
begin
@goto st108

end

end
begin
@goto st98

end
@label st108
p+= 1;
if ( p == pe  )
@goto _test_eof108

end
@label st_case_108
if ( (data[1+(p )]) == 9 )
begin
@goto ctr162

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr146

end
end
if ( 48 <= (data[1+(p )])&& (data[1+(p )])<= 57  )
begin
@goto st108

end

end
begin
@goto st98

end
@label ctr162
begin
output.metadata.score = Nullable(Ragel.@float64_from_anchor!)
end
@goto st109
@label ctr204
begin
output.metadata.score = Nullable{Float64}()
end
@goto st109
@label st109
p+= 1;
if ( p == pe  )
@goto _test_eof109

end
@label st_case_109
if ( (data[1+(p )]) == 10 )
begin
@goto ctr146

end
elseif ( (data[1+(p )]) == 43 )
begin
@goto ctr163

end
elseif ( (data[1+(p )]) == 63 )
begin
@goto ctr163

end
end
if ( 45 <= (data[1+(p )])&& (data[1+(p )])<= 46  )
begin
@goto ctr163

end

end
begin
@goto st98

end
@label ctr163
begin
output.strand = convert(Strand, (Ragel.@char))
end
@goto st110
@label st110
p+= 1;
if ( p == pe  )
@goto _test_eof110

end
@label st_case_110
if ( (data[1+(p )]) == 9 )
begin
@goto st111

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr146

end
end
begin
@goto st98

end
@label st111
p+= 1;
if ( p == pe  )
@goto _test_eof111

end
@label st_case_111
if ( (data[1+(p )]) == 10 )
begin
@goto ctr146

end
elseif ( (data[1+(p )]) == 46 )
begin
@goto ctr165

end
end
if ( 49 <= (data[1+(p )])&& (data[1+(p )])<= 51  )
begin
@goto ctr166

end

end
begin
@goto st98

end
@label ctr165
begin
Ragel.anchor!(state, p)
end
@goto st112
@label st112
p+= 1;
if ( p == pe  )
@goto _test_eof112

end
@label st_case_112
if ( (data[1+(p )]) == 9 )
begin
@goto ctr167

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr146

end
end
begin
@goto st98

end
@label ctr167
begin
output.metadata.phase = Nullable{Int}()
end
@goto st113
@label ctr198
begin
output.metadata.phase = Nullable(Ragel.@int64_from_anchor!)
end
@goto st113
@label st113
p+= 1;
if ( p == pe  )
@goto _test_eof113

end
@label st_case_113
if ( (data[1+(p )]) == 10 )
begin
@goto ctr169

end
elseif ( (data[1+(p )]) == 13 )
begin
@goto ctr170

end
end
begin
@goto ctr168

end
@label ctr168
begin
Ragel.anchor!(state, p)
end
@goto st114
@label ctr170
begin
Ragel.anchor!(state, p)
end
begin
Ragel.@copy_from_anchor!(output.metadata.attributes)
end
@goto st114
@label ctr173
begin
Ragel.@copy_from_anchor!(output.metadata.attributes)
end
@goto st114
@label st114
p+= 1;
if ( p == pe  )
@goto _test_eof114

end
@label st_case_114
if ( (data[1+(p )]) == 10 )
begin
@goto ctr172

end
elseif ( (data[1+(p )]) == 13 )
begin
@goto ctr173

end
end
begin
@goto st114

end
@label ctr177
begin
input.state.linenum += 1
end
@goto st147
@label ctr169
begin
input.state.linenum += 1
end
begin
Ragel.anchor!(state, p)
end
begin
Ragel.@copy_from_anchor!(output.metadata.attributes)
end
@goto st147
@label ctr172
begin
input.state.linenum += 1
end
begin
Ragel.@copy_from_anchor!(output.metadata.attributes)
end
@goto st147
@label st147
p+= 1;
if ( p == pe  )
@goto _test_eof147

end
@label st_case_147
if ( (data[1+(p )]) == 9 )
begin
@goto ctr221

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr29

end
elseif ( (data[1+(p )]) == 11 )
begin
@goto st20

end
elseif ( (data[1+(p )]) == 13 )
begin
@goto st21

end
elseif ( (data[1+(p )]) == 32 )
begin
@goto ctr222

end
elseif ( (data[1+(p )]) == 35 )
begin
@goto ctr224

end
end
if ( 33 <= (data[1+(p )])&& (data[1+(p )])<= 126  )
begin
@goto ctr223

end

end
begin
@goto st0

end
@label ctr224
begin
directive = Ragel.@ascii_from_anchor!
if startswith(directive, "##gff-version")
# ##gff-version 3.2.1
input.version = VersionNumber(split(directive, r"\s+")[2])
elseif startswith(directive, "##sequence-region")
# ##sequence-region seqid start end
vals = split(directive, r"\s+")
push!(input.sequence_regions,
Interval(vals[2], parse(Int, vals[3]), parse(Int, vals[4])))
else
# TODO: record other directives
end
end
begin
Ragel.anchor!(state, p)
end
begin
yield = true
Ragel.@anchor!
begin
p+= 1;
cs = 115;
@goto _out

end

end
@goto st115
@label st115
p+= 1;
if ( p == pe  )
@goto _test_eof115

end
@label st_case_115
if ( (data[1+(p )]) == 9 )
begin
@goto ctr110

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr111

end
elseif ( (data[1+(p )]) == 35 )
begin
@goto st116

end
end
if ( 32 <= (data[1+(p )])&& (data[1+(p )])<= 126  )
begin
@goto st71

end

end
begin
@goto st72

end
@label st116
p+= 1;
if ( p == pe  )
@goto _test_eof116

end
@label st_case_116
if ( (data[1+(p )]) == 9 )
begin
@goto ctr176

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr177

end
end
if ( 32 <= (data[1+(p )])&& (data[1+(p )])<= 126  )
begin
@goto st116

end

end
begin
@goto st117

end
@label st117
p+= 1;
if ( p == pe  )
@goto _test_eof117

end
@label st_case_117
if ( (data[1+(p )])== 10  )
begin
@goto ctr177

end

end
begin
@goto st117

end
@label ctr176
begin
Ragel.@copy_from_anchor!(output.seqname)
end
@goto st118
@label st118
p+= 1;
if ( p == pe  )
@goto _test_eof118

end
@label st_case_118
if ( (data[1+(p )]) == 9 )
begin
@goto ctr178

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr177

end
end
if ( 32 <= (data[1+(p )])&& (data[1+(p )])<= 126  )
begin
@goto ctr179

end

end
begin
@goto st117

end
@label ctr178
begin
Ragel.anchor!(state, p)
end
begin
Ragel.@copy_from_anchor!(output.metadata.source)
end
@goto st119
@label ctr202
begin
Ragel.@copy_from_anchor!(output.metadata.source)
end
@goto st119
@label st119
p+= 1;
if ( p == pe  )
@goto _test_eof119

end
@label st_case_119
if ( (data[1+(p )]) == 9 )
begin
@goto ctr180

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr177

end
end
if ( 32 <= (data[1+(p )])&& (data[1+(p )])<= 126  )
begin
@goto ctr181

end

end
begin
@goto st117

end
@label ctr180
begin
Ragel.anchor!(state, p)
end
begin
Ragel.@copy_from_anchor!(output.metadata.kind)
end
@goto st120
@label ctr200
begin
Ragel.@copy_from_anchor!(output.metadata.kind)
end
@goto st120
@label st120
p+= 1;
if ( p == pe  )
@goto _test_eof120

end
@label st_case_120
if ( (data[1+(p )])== 10  )
begin
@goto ctr177

end

end
if ( 48 <= (data[1+(p )])&& (data[1+(p )])<= 57  )
begin
@goto ctr182

end

end
begin
@goto st117

end
@label ctr182
begin
Ragel.anchor!(state, p)
end
@goto st121
@label st121
p+= 1;
if ( p == pe  )
@goto _test_eof121

end
@label st_case_121
if ( (data[1+(p )]) == 9 )
begin
@goto ctr183

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr177

end
end
if ( 48 <= (data[1+(p )])&& (data[1+(p )])<= 57  )
begin
@goto st121

end

end
begin
@goto st117

end
@label ctr183
begin
output.first = Ragel.@int64_from_anchor!
end
@goto st122
@label st122
p+= 1;
if ( p == pe  )
@goto _test_eof122

end
@label st_case_122
if ( (data[1+(p )])== 10  )
begin
@goto ctr177

end

end
if ( 48 <= (data[1+(p )])&& (data[1+(p )])<= 57  )
begin
@goto ctr185

end

end
begin
@goto st117

end
@label ctr185
begin
Ragel.anchor!(state, p)
end
@goto st123
@label st123
p+= 1;
if ( p == pe  )
@goto _test_eof123

end
@label st_case_123
if ( (data[1+(p )]) == 9 )
begin
@goto ctr186

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr177

end
end
if ( 48 <= (data[1+(p )])&& (data[1+(p )])<= 57  )
begin
@goto st123

end

end
begin
@goto st117

end
@label ctr186
begin
output.last = Ragel.@int64_from_anchor!
end
@goto st124
@label st124
p+= 1;
if ( p == pe  )
@goto _test_eof124

end
@label st_case_124
if ( (data[1+(p )]) == 10 )
begin
@goto ctr177

end
elseif ( (data[1+(p )]) == 43 )
begin
@goto ctr188

end
elseif ( (data[1+(p )]) == 45 )
begin
@goto ctr188

end
elseif ( (data[1+(p )]) == 46 )
begin
@goto ctr189

end
end
begin
@goto st117

end
@label ctr188
begin
Ragel.anchor!(state, p)
end
@goto st125
@label st125
p+= 1;
if ( p == pe  )
@goto _test_eof125

end
@label st_case_125
if ( (data[1+(p )]) == 10 )
begin
@goto ctr177

end
elseif ( (data[1+(p )]) == 46 )
begin
@goto st126

end
end
if ( 48 <= (data[1+(p )])&& (data[1+(p )])<= 57  )
begin
@goto st133

end

end
begin
@goto st117

end
@label st126
p+= 1;
if ( p == pe  )
@goto _test_eof126

end
@label st_case_126
if ( (data[1+(p )])== 10  )
begin
@goto ctr177

end

end
if ( 48 <= (data[1+(p )])&& (data[1+(p )])<= 57  )
begin
@goto st127

end

end
begin
@goto st117

end
@label st127
p+= 1;
if ( p == pe  )
@goto _test_eof127

end
@label st_case_127
if ( (data[1+(p )]) == 9 )
begin
@goto ctr193

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr177

end
end
if ( 48 <= (data[1+(p )])&& (data[1+(p )])<= 57  )
begin
@goto st127

end

end
begin
@goto st117

end
@label ctr193
begin
output.metadata.score = Nullable(Ragel.@float64_from_anchor!)
end
@goto st128
@label ctr199
begin
output.metadata.score = Nullable{Float64}()
end
@goto st128
@label st128
p+= 1;
if ( p == pe  )
@goto _test_eof128

end
@label st_case_128
if ( (data[1+(p )]) == 10 )
begin
@goto ctr177

end
elseif ( (data[1+(p )]) == 43 )
begin
@goto ctr194

end
elseif ( (data[1+(p )]) == 63 )
begin
@goto ctr194

end
end
if ( 45 <= (data[1+(p )])&& (data[1+(p )])<= 46  )
begin
@goto ctr194

end

end
begin
@goto st117

end
@label ctr194
begin
output.strand = convert(Strand, (Ragel.@char))
end
@goto st129
@label st129
p+= 1;
if ( p == pe  )
@goto _test_eof129

end
@label st_case_129
if ( (data[1+(p )]) == 9 )
begin
@goto st130

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr177

end
end
begin
@goto st117

end
@label st130
p+= 1;
if ( p == pe  )
@goto _test_eof130

end
@label st_case_130
if ( (data[1+(p )]) == 10 )
begin
@goto ctr177

end
elseif ( (data[1+(p )]) == 46 )
begin
@goto ctr196

end
end
if ( 49 <= (data[1+(p )])&& (data[1+(p )])<= 51  )
begin
@goto ctr197

end

end
begin
@goto st117

end
@label ctr196
begin
Ragel.anchor!(state, p)
end
@goto st131
@label st131
p+= 1;
if ( p == pe  )
@goto _test_eof131

end
@label st_case_131
if ( (data[1+(p )]) == 9 )
begin
@goto ctr167

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr177

end
end
begin
@goto st117

end
@label ctr197
begin
Ragel.anchor!(state, p)
end
@goto st132
@label st132
p+= 1;
if ( p == pe  )
@goto _test_eof132

end
@label st_case_132
if ( (data[1+(p )]) == 9 )
begin
@goto ctr198

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr177

end
end
begin
@goto st117

end
@label st133
p+= 1;
if ( p == pe  )
@goto _test_eof133

end
@label st_case_133
if ( (data[1+(p )]) == 9 )
begin
@goto ctr193

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr177

end
elseif ( (data[1+(p )]) == 46 )
begin
@goto st126

end
end
if ( 48 <= (data[1+(p )])&& (data[1+(p )])<= 57  )
begin
@goto st133

end

end
begin
@goto st117

end
@label ctr189
begin
Ragel.anchor!(state, p)
end
@goto st134
@label st134
p+= 1;
if ( p == pe  )
@goto _test_eof134

end
@label st_case_134
if ( (data[1+(p )]) == 9 )
begin
@goto ctr199

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr177

end
end
begin
@goto st117

end
@label ctr181
begin
Ragel.anchor!(state, p)
end
@goto st135
@label st135
p+= 1;
if ( p == pe  )
@goto _test_eof135

end
@label st_case_135
if ( (data[1+(p )]) == 9 )
begin
@goto ctr200

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr177

end
end
if ( 32 <= (data[1+(p )])&& (data[1+(p )])<= 126  )
begin
@goto st135

end

end
begin
@goto st117

end
@label ctr179
begin
Ragel.anchor!(state, p)
end
@goto st136
@label st136
p+= 1;
if ( p == pe  )
@goto _test_eof136

end
@label st_case_136
if ( (data[1+(p )]) == 9 )
begin
@goto ctr202

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr177

end
end
if ( 32 <= (data[1+(p )])&& (data[1+(p )])<= 126  )
begin
@goto st136

end

end
begin
@goto st117

end
@label ctr166
begin
Ragel.anchor!(state, p)
end
@goto st137
@label st137
p+= 1;
if ( p == pe  )
@goto _test_eof137

end
@label st_case_137
if ( (data[1+(p )]) == 9 )
begin
@goto ctr198

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr146

end
end
begin
@goto st98

end
@label st138
p+= 1;
if ( p == pe  )
@goto _test_eof138

end
@label st_case_138
if ( (data[1+(p )]) == 9 )
begin
@goto ctr162

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr146

end
elseif ( (data[1+(p )]) == 46 )
begin
@goto st107

end
end
if ( 48 <= (data[1+(p )])&& (data[1+(p )])<= 57  )
begin
@goto st138

end

end
begin
@goto st98

end
@label ctr158
begin
Ragel.anchor!(state, p)
end
@goto st139
@label st139
p+= 1;
if ( p == pe  )
@goto _test_eof139

end
@label st_case_139
if ( (data[1+(p )]) == 9 )
begin
@goto ctr204

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr146

end
end
begin
@goto st98

end
@label ctr150
begin
Ragel.anchor!(state, p)
end
@goto st140
@label st140
p+= 1;
if ( p == pe  )
@goto _test_eof140

end
@label st_case_140
if ( (data[1+(p )]) == 9 )
begin
@goto ctr205

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr146

end
end
if ( 32 <= (data[1+(p )])&& (data[1+(p )])<= 126  )
begin
@goto st140

end

end
begin
@goto st98

end
@label ctr148
begin
Ragel.anchor!(state, p)
end
@goto st141
@label st141
p+= 1;
if ( p == pe  )
@goto _test_eof141

end
@label st_case_141
if ( (data[1+(p )]) == 9 )
begin
@goto ctr207

end
elseif ( (data[1+(p )]) == 10 )
begin
@goto ctr146

end
end
if ( 32 <= (data[1+(p )])&& (data[1+(p )])<= 126  )
begin
@goto st141

end

end
begin
@goto st98

end
@label st_out
@label _test_eof1
cs = 1;
@goto _test_eof
@label _test_eof2
cs = 2;
@goto _test_eof
@label _test_eof3
cs = 3;
@goto _test_eof
@label _test_eof4
cs = 4;
@goto _test_eof
@label _test_eof5
cs = 5;
@goto _test_eof
@label _test_eof6
cs = 6;
@goto _test_eof
@label _test_eof7
cs = 7;
@goto _test_eof
@label _test_eof8
cs = 8;
@goto _test_eof
@label _test_eof9
cs = 9;
@goto _test_eof
@label _test_eof10
cs = 10;
@goto _test_eof
@label _test_eof11
cs = 11;
@goto _test_eof
@label _test_eof12
cs = 12;
@goto _test_eof
@label _test_eof13
cs = 13;
@goto _test_eof
@label _test_eof14
cs = 14;
@goto _test_eof
@label _test_eof15
cs = 15;
@goto _test_eof
@label _test_eof16
cs = 16;
@goto _test_eof
@label _test_eof143
cs = 143;
@goto _test_eof
@label _test_eof17
cs = 17;
@goto _test_eof
@label _test_eof18
cs = 18;
@goto _test_eof
@label _test_eof19
cs = 19;
@goto _test_eof
@label _test_eof20
cs = 20;
@goto _test_eof
@label _test_eof21
cs = 21;
@goto _test_eof
@label _test_eof22
cs = 22;
@goto _test_eof
@label _test_eof23
cs = 23;
@goto _test_eof
@label _test_eof24
cs = 24;
@goto _test_eof
@label _test_eof25
cs = 25;
@goto _test_eof
@label _test_eof26
cs = 26;
@goto _test_eof
@label _test_eof27
cs = 27;
@goto _test_eof
@label _test_eof28
cs = 28;
@goto _test_eof
@label _test_eof29
cs = 29;
@goto _test_eof
@label _test_eof30
cs = 30;
@goto _test_eof
@label _test_eof31
cs = 31;
@goto _test_eof
@label _test_eof32
cs = 32;
@goto _test_eof
@label _test_eof33
cs = 33;
@goto _test_eof
@label _test_eof34
cs = 34;
@goto _test_eof
@label _test_eof35
cs = 35;
@goto _test_eof
@label _test_eof36
cs = 36;
@goto _test_eof
@label _test_eof37
cs = 37;
@goto _test_eof
@label _test_eof38
cs = 38;
@goto _test_eof
@label _test_eof39
cs = 39;
@goto _test_eof
@label _test_eof40
cs = 40;
@goto _test_eof
@label _test_eof41
cs = 41;
@goto _test_eof
@label _test_eof42
cs = 42;
@goto _test_eof
@label _test_eof43
cs = 43;
@goto _test_eof
@label _test_eof44
cs = 44;
@goto _test_eof
@label _test_eof45
cs = 45;
@goto _test_eof
@label _test_eof46
cs = 46;
@goto _test_eof
@label _test_eof47
cs = 47;
@goto _test_eof
@label _test_eof48
cs = 48;
@goto _test_eof
@label _test_eof49
cs = 49;
@goto _test_eof
@label _test_eof50
cs = 50;
@goto _test_eof
@label _test_eof51
cs = 51;
@goto _test_eof
@label _test_eof52
cs = 52;
@goto _test_eof
@label _test_eof53
cs = 53;
@goto _test_eof
@label _test_eof144
cs = 144;
@goto _test_eof
@label _test_eof54
cs = 54;
@goto _test_eof
@label _test_eof55
cs = 55;
@goto _test_eof
@label _test_eof56
cs = 56;
@goto _test_eof
@label _test_eof57
cs = 57;
@goto _test_eof
@label _test_eof58
cs = 58;
@goto _test_eof
@label _test_eof59
cs = 59;
@goto _test_eof
@label _test_eof60
cs = 60;
@goto _test_eof
@label _test_eof61
cs = 61;
@goto _test_eof
@label _test_eof62
cs = 62;
@goto _test_eof
@label _test_eof63
cs = 63;
@goto _test_eof
@label _test_eof64
cs = 64;
@goto _test_eof
@label _test_eof65
cs = 65;
@goto _test_eof
@label _test_eof66
cs = 66;
@goto _test_eof
@label _test_eof67
cs = 67;
@goto _test_eof
@label _test_eof68
cs = 68;
@goto _test_eof
@label _test_eof69
cs = 69;
@goto _test_eof
@label _test_eof70
cs = 70;
@goto _test_eof
@label _test_eof145
cs = 145;
@goto _test_eof
@label _test_eof71
cs = 71;
@goto _test_eof
@label _test_eof72
cs = 72;
@goto _test_eof
@label _test_eof73
cs = 73;
@goto _test_eof
@label _test_eof74
cs = 74;
@goto _test_eof
@label _test_eof75
cs = 75;
@goto _test_eof
@label _test_eof76
cs = 76;
@goto _test_eof
@label _test_eof77
cs = 77;
@goto _test_eof
@label _test_eof78
cs = 78;
@goto _test_eof
@label _test_eof79
cs = 79;
@goto _test_eof
@label _test_eof80
cs = 80;
@goto _test_eof
@label _test_eof81
cs = 81;
@goto _test_eof
@label _test_eof82
cs = 82;
@goto _test_eof
@label _test_eof83
cs = 83;
@goto _test_eof
@label _test_eof84
cs = 84;
@goto _test_eof
@label _test_eof85
cs = 85;
@goto _test_eof
@label _test_eof86
cs = 86;
@goto _test_eof
@label _test_eof87
cs = 87;
@goto _test_eof
@label _test_eof88
cs = 88;
@goto _test_eof
@label _test_eof89
cs = 89;
@goto _test_eof
@label _test_eof90
cs = 90;
@goto _test_eof
@label _test_eof91
cs = 91;
@goto _test_eof
@label _test_eof92
cs = 92;
@goto _test_eof
@label _test_eof93
cs = 93;
@goto _test_eof
@label _test_eof94
cs = 94;
@goto _test_eof
@label _test_eof95
cs = 95;
@goto _test_eof
@label _test_eof96
cs = 96;
@goto _test_eof
@label _test_eof97
cs = 97;
@goto _test_eof
@label _test_eof98
cs = 98;
@goto _test_eof
@label _test_eof146
cs = 146;
@goto _test_eof
@label _test_eof99
cs = 99;
@goto _test_eof
@label _test_eof100
cs = 100;
@goto _test_eof
@label _test_eof101
cs = 101;
@goto _test_eof
@label _test_eof102
cs = 102;
@goto _test_eof
@label _test_eof103
cs = 103;
@goto _test_eof
@label _test_eof104
cs = 104;
@goto _test_eof
@label _test_eof105
cs = 105;
@goto _test_eof
@label _test_eof106
cs = 106;
@goto _test_eof
@label _test_eof107
cs = 107;
@goto _test_eof
@label _test_eof108
cs = 108;
@goto _test_eof
@label _test_eof109
cs = 109;
@goto _test_eof
@label _test_eof110
cs = 110;
@goto _test_eof
@label _test_eof111
cs = 111;
@goto _test_eof
@label _test_eof112
cs = 112;
@goto _test_eof
@label _test_eof113
cs = 113;
@goto _test_eof
@label _test_eof114
cs = 114;
@goto _test_eof
@label _test_eof147
cs = 147;
@goto _test_eof
@label _test_eof115
cs = 115;
@goto _test_eof
@label _test_eof116
cs = 116;
@goto _test_eof
@label _test_eof117
cs = 117;
@goto _test_eof
@label _test_eof118
cs = 118;
@goto _test_eof
@label _test_eof119
cs = 119;
@goto _test_eof
@label _test_eof120
cs = 120;
@goto _test_eof
@label _test_eof121
cs = 121;
@goto _test_eof
@label _test_eof122
cs = 122;
@goto _test_eof
@label _test_eof123
cs = 123;
@goto _test_eof
@label _test_eof124
cs = 124;
@goto _test_eof
@label _test_eof125
cs = 125;
@goto _test_eof
@label _test_eof126
cs = 126;
@goto _test_eof
@label _test_eof127
cs = 127;
@goto _test_eof
@label _test_eof128
cs = 128;
@goto _test_eof
@label _test_eof129
cs = 129;
@goto _test_eof
@label _test_eof130
cs = 130;
@goto _test_eof
@label _test_eof131
cs = 131;
@goto _test_eof
@label _test_eof132
cs = 132;
@goto _test_eof
@label _test_eof133
cs = 133;
@goto _test_eof
@label _test_eof134
cs = 134;
@goto _test_eof
@label _test_eof135
cs = 135;
@goto _test_eof
@label _test_eof136
cs = 136;
@goto _test_eof
@label _test_eof137
cs = 137;
@goto _test_eof
@label _test_eof138
cs = 138;
@goto _test_eof
@label _test_eof139
cs = 139;
@goto _test_eof
@label _test_eof140
cs = 140;
@goto _test_eof
@label _test_eof141
cs = 141;
@goto _test_eof
@label _test_eof
begin

end
if ( p == eof  )
begin
if ( cs  == 143 )
elseif ( cs  == 145 )
begin
yield = true
Ragel.@anchor!
begin
p+= 1;
cs = 0;
@goto _out

end

end

break;
elseif ( cs  == 146 )
begin
directive = Ragel.@ascii_from_anchor!
if startswith(directive, "##gff-version")
# ##gff-version 3.2.1
input.version = VersionNumber(split(directive, r"\s+")[2])
elseif startswith(directive, "##sequence-region")
# ##sequence-region seqid start end
vals = split(directive, r"\s+")
push!(input.sequence_regions,
Interval(vals[2], parse(Int, vals[3]), parse(Int, vals[4])))
else
# TODO: record other directives
end
end

break;
elseif ( cs  == 147 )
begin
directive = Ragel.@ascii_from_anchor!
if startswith(directive, "##gff-version")
# ##gff-version 3.2.1
input.version = VersionNumber(split(directive, r"\s+")[2])
elseif startswith(directive, "##sequence-region")
# ##sequence-region seqid start end
vals = split(directive, r"\s+")
push!(input.sequence_regions,
Interval(vals[2], parse(Int, vals[3]), parse(Int, vals[4])))
else
# TODO: record other directives
end
end
begin
yield = true
Ragel.@anchor!
begin
p+= 1;
cs = 0;
@goto _out

end

end

break;
end

end

end
@label _out
begin

end

end
end)
